--- #YAML:1.0
name:               Padre-Plugin-Template
version:            0.1
abstract:           Use external tools with Padre
author:
    - Gregory Siems <gsiems@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Which:          0
    Padre:                0.43
    Padre::Plugin::Shell::Base:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
